### ISSUE TITLE
Configuring colors?

### ISSUE THREAD

**Issue by liar666** [manateelazycat/awesome-tab#101]
In the docs, you write:

> You can customize terminal tab face by below options:
>     awesome-tab-terminal-dark-select-background-color
>     awesome-tab-terminal-dark-select-foreground-color
>     awesome-tab-terminal-dark-unselect-background-color
>     awesome-tab-terminal-dark-unselect-foreground-color
>     awesome-tab-terminal-light-select-background-color
>     awesome-tab-terminal-light-select-foreground-color
>     awesome-tab-terminal-light-unselect-background-color
>     awesome-tab-terminal-light-unselect-foreground-color

I've tried hundreds of things (with `custom-set-faces`, `setq`), but the colors do not change. Can you provide a few example `.emacs` lines?

**Comment by liar666** [comment]
OK. So now, I get some results, adding the following lines in `.emacs`:
```
(custom-set-variables
 '(awesome-tab-dark-selected-background-color "white")
 '(awesome-tab-dark-selected-foreground-color "dark magenta")
)
```
It gave me the following result:
![colors_001](https://user-images.githubusercontent.com/3216927/97467951-060ec080-1945-11eb-9ba8-bf1ec8abec1c.png)

As can be seen:
- The foreground color worked, but not the background one
- If you look at the mini-buffer, there's no other completion to `awesome-tab--dark` than `awesome-tab-dark-selected-foreground-color` in the variables known to emacs
- Also, I've tried the same config from `config.org` instead of `.emacs`, it did not work at all...

In the end, I `git pull`'ed my local copy of `awesome-tab`. Now, I don't have any tab that show when starting emacs. When I try to `M-x load-file awesome-tab.el`, I get error: `set-face-attribute: Invalid face: tab-line`

FYI: emacs v. 26.3

**Comment by manateelazycat** [comment]
Fix newest version.

**Comment by liar666** [comment]
Hi again,
Thanks for you quick response/actions.
I can now run awesome-tab again.
Unfortunately, I still cannot change `awesome-tab-dark-selected-background-color` (nor  `awesome-tab-light-selected-background-color`) :{
