### ISSUE TITLE
Awesome tab not working anymore: "set-face-attribute: Invalid face: tab-line"

### ISSUE THREAD

**Issue by liar666** [manateelazycat/awesome-tab#102]
Hi, I just `git pull\'ed my local copy of awesome-tab.

Now, I don't have any tab that show when starting emacs.

When I try to `M-x load-file awesome-tab.el`, I get error: `set-face-attribute: Invalid face: tab-line`

FYI: emacs v. 26.3

**Comment by manateelazycat** [comment]
Fixed in newest version
