### ISSUE TITLE
awesome-tab 造成 helm 显示异常。

### ISSUE THREAD

**Issue by zw963** [manateelazycat/awesome-tab#108]
见这个帖子。

https://emacs-china.org/t/eaf-opening/18335/25

我猜你对 helm 不感兴趣，但是我通过一个一个测试出来的结果，就是 awesome-tab broken 了 helm 的显示。

这是我有关 awesome-tab 的配置，请看以下是设置错误，还是两个包冲突。

**Comment by manateelazycat** [comment]
为什么不是 helm 的问题呢？

Snails和Ivy都没问题，Selectrum 也没问题。

我真的不想修复Helm那么复杂的插件，如果定位到确定是 Awesome-Tab 的问题我愿意修复，但是我不想去研究Helm

**Comment by zw963** [comment]
在重试了最新版本的 awesome-tab 之后，似乎和 helm 不兼容的问题已经修复。

感谢社区的贡献。
