### ISSUE TITLE
Is there some customizable variable to control the tabbar height? thx!

### ISSUE THREAD

**Issue by SyrakuShaikh** [manateelazycat/awesome-tab#11]
this is an awesome package. Thank you!

I use it along with spacemacs and for my laptop's screen, the tabbar is somewhat too high, so is there some variable that I can customize to control its height?

**Comment by SyrakuShaikh** [comment]
or, as an alternate, maybe some function to switch on/off *awesome-tab*. 
It seems that ```awesome-tab-mode``` does not work for temporarily switching on/off.

**Comment by yqrashawn** [comment]
You can use `defface` to customize the height.
https://github.com/manateelazycat/awesome-tab/blob/master/awesome-tab.el#L494

**Comment by SyrakuShaikh** [comment]
I'm not sure if the following is the best way. But, it's simple and works.
```elisp
(face-spec-set
 'awesome-tab-default
 '((t
    (:inherit default :height 0.9))))
```

**Comment by manateelazycat** [comment]
Yes, it's right way
