### ISSUE TITLE
awesome-tab has conflict with lsp-mode

### ISSUE THREAD

**Issue by lyjdwh** [manateelazycat/awesome-tab#111]
emacs 29.05  最近awesome-tab 和 lsp-mode 同时用，会报错。

猜测和 lsp的 headerline-breadcrumb有冲突 ，把 `(setq lsp-headerline-breadcrumb-enable nil)` 依然不行

使用emacs -Q 测试依然报这个错。
```
Error during redisplay: (eval (awesome-tab-line)) signaled (wrong-type-argument stringp (Git "xxxx")) 
```

**Comment by manateelazycat** [comment]
用 sort-tab.el 吧，为啥不是 lsp-mode 和 awesome-tab 冲突呢？ 其实应该报给 lsp-mode 这个bug
