### ISSUE TITLE
awesome-tab 在 Emacs 29.0.50 打开 git 仓库下的文件报错

### ISSUE THREAD

**Issue by number317** [manateelazycat/awesome-tab#112]
emacs 版本
![image](https://user-images.githubusercontent.com/15346773/173482366-7600ddc8-9348-44e9-a519-5da842f46506.png)

测试配置 test.el
```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/awesome-tab")
(require 'awesome-tab)
(awesome-tab-mode t)
```
打开普通文件（不带有 git 信息）
```bash
emacs -q -l test.el ~/simple.txt
```
结果：awesome-tab 正常渲染
![image](https://user-images.githubusercontent.com/15346773/173482924-0406aa1a-55ce-4331-9ef0-58e2dee52c96.png)

打开 git 仓库下文件

```bash
emacs -q -l test.el ~/Codes/ssh-tool/README.md
```
结果：awesome-tab 无法正常渲染
![image](https://user-images.githubusercontent.com/15346773/173483301-f386137a-e196-483f-8eab-20d947dc70c2.png)

报错信息：
```
Error during redisplay: (eval (awesome-tab-line)) signaled (wrong-type-argument stringp (Git "~/Codes/ssh-tool/")) [32 times]
```
执行 `toggle-debugger-on-error` 之后报错信息也没有啥变化

尝试了修改源码，奈何 elisp 水平太菜，没有得到什么有用信息，只能求助于作者大佬

**Comment by manateelazycat** [comment]
应该是29 project-current API改了吧

**Comment by number317** [comment]
> 应该是29 project-current API改了吧

经过测试发现确实是改了
28版本的执行结果
![image](https://user-images.githubusercontent.com/15346773/173506533-b97e5062-cc21-4200-b0cc-cc96cf22a606.png)


29版本的执行结果
![image](https://user-images.githubusercontent.com/15346773/173507020-dffd1ac1-5aa0-4d05-8552-da23a61c2bd7.png)


我本地把 project-current 用到的地方改成这样就好了，但这样改在 28 版本不适用。
![image](https://user-images.githubusercontent.com/15346773/173506079-5a0f1ffc-dc49-4c79-abe8-29435d7796b0.png)

附上 29 版本的 project-current 说明
![image](https://user-images.githubusercontent.com/15346773/173508566-79ca41b2-ffdf-46c9-8a5b-03960fcf3877.png)

**Comment by manateelazycat** [comment]
欢迎提交兼容 28 和 29 的补丁，我暂时不用 29

**Comment by number317** [comment]
我有空试试，不怎么写 elisp，感觉写起来有点累，括号看花眼

**Comment by manateelazycat** [comment]
已经修复了
