### ISSUE TITLE
在 company-box 的 child frame 中无法隐藏 tab 显示？

### ISSUE THREAD

**Issue by QuarterHeaven** [manateelazycat/awesome-tab#116]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/41909950/201816796-1bbca279-a475-480c-801b-bd9293900b1d.png">
我试着在 awesome-tab-hide-tab 里加入了 *company-box 前缀，但是还是显示了出来。

**Comment by manateelazycat** [comment]
这个是company-box自己不要设置header-line吧。

但是我觉得你的问题是你忽略了星号前面的空格导致的。

**Comment by QuarterHeaven** [comment]
确实是忽略了星号前面的空格，加上就好了
