### ISSUE TITLE
如何隐藏ediff-mode对比窗口中的buffer？

### ISSUE THREAD

**Issue by archcst** [manateelazycat/awesome-tab#118]
Hi manateelazycat,

做了一些配置后，awesome-tab已经常驻我的emacs并能满足我90%以上的使用场景了，感谢您的工作！

当下有个稍显不完美之处，当在magit中按e启动ediff后，ediff会将frame分成三个window，使用awesome-tab后每个window都有tab，占据了较大的空间如下图：

<img width="1135" alt="image" src="https://github.com/manateelazycat/awesome-tab/assets/41679407/cdd536b7-146a-46ff-ac17-b7ef2b6ca6e7">

我尝试通过 derived-mode 来隐藏这些 tab，但未达到目的：

```elisp
;;;; hide tab
(defun +awesome-tab/hide-tab-function (BUFFER)
  "Awesome tab hide tab filter.  BUFFER is the buffer name."
  (let ((name (format "%s" BUFFER)))
    (or
     (derived-mode-p 'ediff-mode) ;;    <<<<<<< 不生效
     (string-prefix-p "*helm" name) ;;   <<<<<<< 以下均生效
     (string-prefix-p "*Help*" name)
     (string-prefix-p "*Compile-Log*" name)
     (string-prefix-p "*lsp" name)
     (string-equal "*Neotree*" name)
     (string-match-p ".*\*undo-tree*" name)
     (string-match-p ".*\*which-key*" name)
     (string-match-p ".*\*Treemacs-Scoped-Buffer.*" name))))

(setq awesome-tab-hide-tab-function '+awesome-tab/hide-tab-function)
```

当查看 `C-h m` 后，似乎并不是 awesome-tab-hide-tab-function 的代码问题，而是 ediff 打开的是三个正常的buffer：

<img width="1129" alt="image" src="https://github.com/manateelazycat/awesome-tab/assets/41679407/eae24667-aca5-4738-95d2-600c93ae5f3d">

在此情况下，请问有没有办法实现将其隐藏掉？

**Comment by manateelazycat** [comment]
尝试一下 awesometab-hide-tabs-hooks

我现在不用awesome-tab了， 我主要用 sort-tab , sort-tab 可以按照使用频率排序标签， 大大减少我找标签的时间， 更方便。

**Comment by archcst** [comment]
感谢及时回复，

请问sort-tab相对于awesome-tab是增量升级的吗，sort-tab中是否保留了group、hide、以及您提到的hide-hook等特性？

**Comment by manateelazycat** [comment]
sort-tab 有隐藏标签的自定义功能， 但是 sort-tab 主要是按照使用频率混合排序， 保证经常编辑的标签就在左边， 没有 group 的功能， 这是和awesome-tab的差别。

awsome-tab 适合多个工程项目有序切换， sort-tab 适合不同文件混杂一起快速 hacking

**Comment by manateelazycat** [comment]
先关闭，有问题请重开issue
