### ISSUE TITLE
A bug in function 'awesome-tab-line'

### ISSUE THREAD

**Issue by kaiwk** [manateelazycat/awesome-tab#12]
# Problem

I have customization to hide tab bar in the specific buffer, such as '\*Message\*'

``` elisp
(require 'dash)
(add-to-list 'awesome-tab-inhibit-functions
             (lambda ()
               (or (member major-mode '(helm-major-mode
                                        help-mode
                                        debugger-mode
                                        compilation-mode))
                   (-filter (lambda (regex) (string-match regex (buffer-name)))
                            my--ignored-buffer-regex))))
```

When I open "\*Message\*" buffer, there still an empty header line, like below:

![before](https://user-images.githubusercontent.com/10190397/51440089-f0934e00-1cfd-11e9-81bd-f5c09e0a9dbe.png)

But if I move the cursor or click in this buffer, the header line will be gone immediately. On Mac OSX, this behavior may not be reproducible. The code in Reproduction can show the idea, it works on both Mac OSX and Linux.

# Reproduction 

I checked the function `awesome-tab-line`,  this function has a statement `(setq header-line-format nil)`. That means, when we filter buffers, the default header line will like below:

```elisp
(setq-default header-line-format '(:eval ((lambda () (setq header-line-format nil)))))
```

I tested the code above, and the behavior is the same as the problem I met. 

# Environment
ArchLinux, Emacs 26.1

**Comment by manateelazycat** [comment]
@kaiwk 

<img width="886" alt="2019-01-24 7 59 47" src="https://user-images.githubusercontent.com/237487/51676820-be8e2e80-2012-11e9-92dc-3bab82998a0f.png">
You can fixed this problem like above code
