### ISSUE TITLE
Melpa?

### ISSUE THREAD

**Issue by errge** [manateelazycat/awesome-tab#13]
Hey, do you have any plans of releasing this to melpa?

**Comment by manateelazycat** [comment]
no, i don't like melpa

thanks

**Comment by jcs090218** [comment]
@manateelazycat I wonder what is wrong with melpa? Just curious.

**Comment by manateelazycat** [comment]
just not like,no reason

**Comment by jcs090218** [comment]
Just to be clear, you personally don't like melpa but would you mind if someone forked your work and released to melpa? Or you just completely does not want any contact with melpa? I really like your work here but also respect what you (the author) willing to grant. Or do you accept PR to make this package to release under melpa?

**Comment by manateelazycat** [comment]
I just completely does not want any contact with melpa

that's my point

thanks

**Comment by jcs090218** [comment]
All good! :D
