### ISSUE TITLE
切换buffer时，如果此buffer A与切换前的buffer B 是同一个group,能否把A 挪到B 之后

### ISSUE THREAD

**Issue by jixiuf** [manateelazycat/awesome-tab#15]
这个思路不知道成不成熟
切换buffer时，如果此buffer A与切换前的buffer B 是同一个group,能否把A 挪到B 之后，
这样我想回到原buffer时，只需要awesome-tab-backward即可 
这个思路有些类似于 https://github.com/manateelazycat/awesome-tab/commit/1cc31c39ae7e845fba44fc2a9eb5d0b657b57374 这次的提交（Open new tab on right of current one）

或者干脆 每次刷新tab列表的时候，直接按(buffer-list)的倒序重建当前group内的buffer 列表，
这样，当前buffer 始终处于列表的最后一个，而倒数第2个则为我上次访问的buffer，

当然也可以正序排，则当前buffer始终处于列表的第1位

**Comment by manateelazycat** [comment]
我知道你的意思, 其实你想要的就是, 在来回切换两个标签的时候, 相当于这两个标签的内容要来回对比, 在标签多的情况下来回切换方便, 而不用每次都搜索一次.

但是这种便利性的功能, 估计会带来更多困惑, 需要想一想交互细节.

我们大家都先思考一下, 如果觉得没有坑, 到时候可以做, 比较方便.

**Comment by manateelazycat** [comment]
我想了想, 核心的问题是:
1. 怎么才算是切换标签? awesome-tab 访问到? helm ? ibuffer ? find-file?
2. 如果一切换标签就挪动标签的位置, 那些只是想挨个看一下标签的行为就会不断的被这种逻辑所干扰

我知道你的想法, 其实我认为 helm + recent file 也许是一个更简洁和更明确的交互方式.

**Comment by manateelazycat** [comment]
Done by https://github.com/manateelazycat/awesome-tab/commit/c70c0f3ae1f8dd9bf4043ec09931490d76eb6db0
