### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by jixiuf** [manateelazycat/awesome-tab#18]
https://github.com/manateelazycat/awesome-tab/blob/2790852056950bcc275f81a04e3a8b0aa1421ea0/awesome-tab.el#L896
awesome-tab-inhibit-functions 这个变量 重命名之后 这块逻辑受影响吧 

emacs 27上报找不到insert-after这个函数
```
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
```
```
Error in post-command-hook (awesome-tab-adjust-buffer-order): (void-function insert-after)
```

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-tab/commit/614b50da7b7cb89655df2259c2e6ffadabfb1c59
