### ISSUE TITLE
请问tab bar上的虚线可以去掉吗？

### ISSUE THREAD

**Issue by shuxiao9058** [manateelazycat/awesome-tab#19]
如图：
![image](https://user-images.githubusercontent.com/3312525/53691512-87056580-3dba-11e9-9b68-fdf81a66ab93.png)

**Comment by manateelazycat** [comment]
默认主题没有虚线, 请先用 emacs -Q 尝试一次, 如果 emacs -Q 没有问题, 请检查你自己主题的样式
