### ISSUE TITLE
最新版本 awesone-tab 在 emacs 26.1 启动时报错

### ISSUE THREAD

**Issue by zero4drift** [manateelazycat/awesome-tab#22]
emacs 版本
``GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-10-06``

启动时报错信息
``Error in post-command-hook (awesome-tab-adjust-buffer-order): (void-function first)``

**Comment by manateelazycat** [comment]
(require 'cl)

**Comment by zero4drift** [comment]
谢谢。
