### ISSUE TITLE
emacs刚启动不显示tabbar

### ISSUE THREAD

**Issue by liguangsheng** [manateelazycat/awesome-tab#28]
Emacs刚启动时tabbar没有出现，打开新文件也没出现，只有在用awosome的函数(比如awosome-tab-forward)切换buffer后才出现。

![刚启动](https://user-images.githubusercontent.com/8074650/54328671-c6994080-4649-11e9-84fd-f3c86b047927.png)

![切换后](https://user-images.githubusercontent.com/8074650/54328864-74a4ea80-464a-11e9-812e-a7d062fefbdd.png)

我的配置
``` elisp
(use-package awesome-tab
  :straight (awesome-tab
	     :type git
	     :host github
	     :repo "manateelazycat/awesome-tab")
  :config
  (setq awesome-tab-style 'slant
	awesome-tab-cycle-scope 'tabs)
  (awesome-tab-mode t)
  :bind* (("s-<left>"  . awesome-tab-backward)
	  ("s-<right>" . awesome-tab-forward)
	  ("s-<up>"    . awesome-tab-forward-group)
	  ("s-<down>"  . awesome-tab-backward-group))
  )

```

**Comment by manateelazycat** [comment]
请使用 emacs -Q 测试一下, 排除其他配置的影响

我这边测试没有问题, 我自己不用 spacemacs 和 package

如果 emacs -Q 都有问题, 请重新打开此 issue, 谢谢反馈.
