### ISSUE TITLE
Clickable tabs

### ISSUE THREAD

**Issue by p-kolacz** [manateelazycat/awesome-tab#29]
Should tabs be clickable? Because clicking on tabs doesn't do anything.

**Comment by manateelazycat** [comment]
i have remove mouse feature in last week

**Comment by fbob** [comment]
Please could you explain why ?
Is it a design choice or only temporary off ?
I think the mouse feature was great and doesn't hurt  a keyboard usage :)

**Comment by qhuyduong** [comment]
@fbob You can use this simple snippet to have clickable tabs
```el
(defun awesome-tab-click-to-tab (event)
  "Switch to buffer (obtained from EVENT) on clicking header line"
  (interactive "e")
  (let ((selected-tab-name
        (string-trim (car (posn-string (event-start event))))))
    (unless (string-match-p "^%-$" selected-tab-name)
      (switch-to-buffer selected-tab-name))))

;; on linux, make right button show char info on clicked point
(global-set-key [header-line mouse-1] #'awesome-tab-click-to-tab)
```

Have fun!

**Comment by fbob** [comment]
Many thanks @qhuyduong  for your great advice :+1:
