### ISSUE TITLE
tab may not be visible when window is split  horizontally

### ISSUE THREAD

**Issue by levindu** [manateelazycat/awesome-tab#31]
The current tab is at the last of the header line.
When the window is split horizontally, the tab 
is no longer visible.

It is preferable to keep the current tab visible after window splitting.

**Comment by manateelazycat** [comment]
I haven't idea now, look again in a few days.

**Comment by manateelazycat** [comment]
Some logic like this:

(defun awesome-tab-visible-current-tab ()
  (let* ((tabset (awesome-tab-current-tabset))
         visible-buffers)
    (setq visible-buffers (mapcar 'car (awesome-tab-view tabset)))
    (while (not (member (current-buffer) visible-buffers))
      (awesome-tab-scroll (awesome-tab-view tabset) -1)
      (setq visible-buffers (mapcar 'car (awesome-tab-view tabset)))
      )))

But we need write new function instead awesome-tab-view that just return visible tabs in current window.

Currently, awesome-tab-view return all visible tabs in current frame.

**Comment by manateelazycat** [comment]
I usually split the screen up and down, and I rarely encounter this problem.
I don’t have much time to implement this feature that I rarely use recently, sorry.

Welcome to contribute the patch, close this issue first.

**Comment by levindu** [comment]
Thanks for considering this. Nowadays we have widescreen, splitting left and right is more common.
Never mind. I'll have a try to fix this if I cannot bear this.

**Comment by manateelazycat** [comment]
you're welcome. ;)
