### ISSUE TITLE
awesome-tab显示(void-function awesome-tab-separator-separator-height)

### ISSUE THREAD

**Issue by yqu212** [manateelazycat/awesome-tab#35]
在spacemacs下面启用awesome-tab之后spaceline消失了。我看了一下源码。没有找到这个函数定义。

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.9)
Package-Version: 20190625.1437

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-tab/commit/d22f33bd71d5441aba222e550b25132501c949f1
