### ISSUE TITLE
Add a customizable variable for using all-the-icons or not?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tab#37]
Sometimes `all-the-icons` is loaded, but the user don't want `awesome-tab` to use it. For example, `doom-modeline` requires `all-the-icons` explicitly, but the icons won't show in terminal. The user can customize `doom-modeline-icon` to make the modeline doesn't show icons, but `awesome-tab` will try to show them anyway since `all-the-icons` is loaded. Can we have a variable to control this behavior?

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/awesome-tab/commit/b88696c640f78cfaa7cecd9d7a01627320284c48

**Comment by AmaiKinono** [comment]
Thanks!
