### ISSUE TITLE
Only show tabs in active window?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tab#39]
For people using modeline, buffer names are shown at the bottom of every window, so tabs are not needed for inactive windows. Is there anyway to do this?

**Comment by manateelazycat** [comment]
No, I don't think this is a good idea.

awesome-tab-backward-tab-other-window and awesome-tab-forward-tab-other-window is use for scroll tab in other window.

The above command is very useful when you don't want to switch windows but want to switch the tab of other windows.
