### ISSUE TITLE
不能只在当前分组循环切换标签

### ISSUE THREAD

**Issue by LuoPX-15510486969** [manateelazycat/awesome-tab#4]
awesome-tab里面有个变量awesome-tab-scope可以控制只在当前分组循环切换标签还是在所有分组循环切换标签，可是无论设置成tabs还是groups好像都只能在所有分组中循环切换
(custom-set-variables '(awesome-tab-scope tabs))
这是我的设置方式

**Comment by manateelazycat** [comment]
awesome-tab-cycle-scope 选项只影响命令: awesome-tab-backward 和 awesome-tab-forward

如果只想在当前分组中切换标签, 请使用 awesome-tab-backward-tab, awesome-tab-forward-tab
