### ISSUE TITLE
Symbol’s function definition is void: awesome-tab-separator-pattern-defun (Win 10, emacs 27)

### ISSUE THREAD

**Issue by ShuguangSun** [manateelazycat/awesome-tab#41]
When I byte complile aswsome-tab in Emacs -q, I got error message:
```
awesome-tab.el:1408:1:Error: Symbol’s function definition is void: awesome-tab-separator-pattern-defun
```

In GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32)
 of 2019-06-30 built on
Repository revision: f24d47359d9b6621215f20795d585c5024d91783
Repository branch: master
Windowing system distributor 'Microsoft Corp.', version 10.0.15063
System Description: Microsoft Windows 10 Enterprise (v10.0.1703.15063.1868)

**Comment by manateelazycat** [comment]
You need load-file before you compile *.el file.
