### ISSUE TITLE
Misbehavior / Vague documentation of awesome-tab-local-mode

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tab#42]
`awesome-tab-local-mode` switches the visibility of the tabs in local buffer (since it makes buffer-local variable), but the documentation says "toggle local display of the tab bar", which I thought refers to the current window, and this is a more reasonable behavior in my opinion. The user should be thinking of current window when he/she calls this function, but when the same buffer appears on multiple windows in a screen, they are all affected. I think either the behavior or the documentation should be fixed.

**Comment by manateelazycat** [comment]
awesome-tab-local-mode 是因为 tabbar.el 遗留的bug，我觉得应该把 local 相关的代码都删除了。

如果以后大家觉得有新的功能要实现，再写新的代码。

你怎么看？

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/awesome-tab/commit/7e2cc3b191d9da400751f55132ef69168394f968 已经删除了

**Comment by AmaiKinono** [comment]
我没意见。但我觉得其实「仅在当前 window 显示 tab」是个比较普遍的需求。我知道你用 `awesome-tray`，切窗口用 `C-x o`，所以用起来很舒服，但是多数用户是每个窗口都有 modeline 的（比如我就有，主要是希望能看到窗口编号和 buffer 名），不少人用 `window-numbering` 一类工具切换窗口，这样会产生以下问题

- 每个窗口同时有 tab 和 modeline，比较拥挤。
- 有两个以上窗口时，`awesome-tab-backward-tab-other-window` 和 `awesome-tab-forward-tab-other-window` 可能管不到我想管的那个窗口。

我设想的操作方式是：

- 仅在当前窗口显示 tab，使用 `awesome-tab` 提供的快捷键切换。
- 定义一个 hydra，进入这个 hydra 时触发一个函数，使得所有窗口都临时显示 tab，这时可以使用数字键切换窗口，用字母键切换当前窗口的 tab 和分组。

我知道你可能不会满足自己没有的需求，但如果你有思路的话可以告诉我，我很愿意给 `awesome-tab` 加新功能。

**Comment by manateelazycat** [comment]
我主要觉得只在当前窗口显示标签，这个需求比较小众，如果你能加一个选项，同时不能把代码做得很复杂的话，我也乐意接受补丁。

**Comment by AmaiKinono** [comment]
研究了半天也没弄明白怎么只在当前 window 或 buffer 里显示，放弃了 :rofl:
