### ISSUE TITLE
Thoughts on rearranging tabs

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tab#48]
It's good to have frequently used tabs clustering together. awesome-tab previously took the approach to move previous tab near current tab when jump to a tab far away, but this is often not the expected behavior.

Since we have `awesome-tab-ace-jump` now, it's convenient to jump between tabs in current screen. I suggest we create a command to move current tab to the first position, and the rearranging process will be like:

- Occasionally we have to jump to a tab out of current screen. Use helm/ivy/built-in command to do this.
- Move it to the first position.
- As this goes on, most frequently used tabs will be in the first screen.

A "go to the first tab" command is also needed, such that when the user is not on first screen, and decide not to move current tab to the first position, he/she can go back to first screen quickly.

---

我们希望常用的 tab 能聚在一起。之前 awesome-tab 采用了「跳到较远的 tab 时，把前一个 tab 带过来」的机制，但这往往不是想要的。

现在我们有 `awesome-tab-ace-jump` 了，所以在一屏内的 tab 之间跳转都是很方便的。我建议做一个命令，把当前的 tab 移到第一个位置。重排的过程像是：

- 偶尔我们需要跳到不在屏幕上的 tab，这可以用 helm/ivy/自带命令做到。
- 把它移到第一位去。
- 几次之后，最常用的 tab 都在第一屏之内了

我们还需要一个「回到第一个标签」的命令，这样如果用户不在第一屏，也不想把当前 tab 移到第一位，他可以快速返回第一屏。

**Comment by manateelazycat** [comment]
我直接删除了重新排的功能。
https://github.com/manateelazycat/awesome-tab/commit/aefc999cd5f3eb7bee3093c7918ea89e642e5ea3

**Comment by AmaiKinono** [comment]
我说的是「把第一屏外边的 tab 带到第一屏内」的功能，不是自动重排。只要想要的都在第一屏里面，用 ace jump 就很快。

**Comment by manateelazycat** [comment]
自动重排的删掉了，你说的那个功能我们在想想吧。

**Comment by AmaiKinono** [comment]
我写了一篇[博文](https://amaikinono.github.io/introduce-awesome-tab.html)，里面解释了我说的这种操作模式，你可以参考下。

**Comment by manateelazycat** [comment]
@AmaiKinono 我看懂你的意思了， 把awesome-tab-move-current-tab-to-beg这个命令加进来吧，我来合并。
