### ISSUE TITLE
Go back to previous buffer after killing particular buffers?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tab#51]
如题。有时我们用两个窗口对照着写代码，此时如果用一个 `describe-xxx` 系列的命令，另一边的窗口会被 \*Help\* buffer 占掉。kill 这个 buffer 以后，会切换到另一个 Emacs group 的 buffer 中，而我们希望它能自动回到原来看的代码中。那么是否可以增加一个自定义列表，使得该列表中的 buffer 被 kill 之后，自动回到之前的 buffer？

**Comment by manateelazycat** [comment]
这个功能想的不错，要想想有没有坑？

会不会一部分bufffer kill后自动跳转上一个buffer，而大部分buffer kill后切换到另外的group

我对插件的理解是，逻辑一致性大于智能，再想想哈

**Comment by AmaiKinono** [comment]
我找到一个做法：Emacs 自带有 `previous-buffer` 命令，我借助 `ace-window` 的功能写了这个函数：

``` emacs-lisp
(defun my-previous-buffer-other-window ()
  (interactive)
  (aw-select " Ace - Back to Previous Buffer"
             #'aw-switch-to-window)
  (previous-buffer)
  (aw-flip-window))
```

调用时会让我选一个窗口（只有两个窗口时自动选择），然后把那个窗口的 buffer 回滚到上一个。我只要在看完 \*Help\* 信息之后调用这个命令就可以了。

**Comment by manateelazycat** [comment]
那建议自己玩吧，Awesome-Tab做的太智能，普适性不是很好
