### ISSUE TITLE
cond: Too many visible tabs

### ISSUE THREAD

**Issue by jiahut** [manateelazycat/awesome-tab#52]
if  a  group had many tabs, trigger `awesome-tab-ace-jump` will cause  `cond: Too many visible tabs`

when custom variable  `(setq awesome-tab-ace-keys '(?j ?k ?h ?g ?d ?f ))` 

it cause other error like `cl-subseq: Bad bounding indices: 0, 20`

I think the tabs should be truncated when the tabs size more then  16 (4*4)

**Comment by manateelazycat** [comment]
@AmaiKinono Any idea?

**Comment by AmaiKinono** [comment]
I have no access to my PC currently, but I think I know the reason. When `awesome-tab-ace-keys` is set, a setter function is run to update a series of variables, you may want looking into the code. To achieve this, you have to use one of these ways:

- Set it before requiring awesome-tab.
- Use `customize-set-variables`, it detects the setter function and run it.
- Copy the `general-setq` macro from general.el. The explanation is [here], it also runs the setter but is way faster than `customize-set-variables`. I suggest you do this. I basically use this macro whenever I want to set customizable variables, and get rid of most similar problems.

I do think we should mention this problem in README. I'll do it tomorrow.

**Comment by jiahut** [comment]
`customize-set-variables` not works well with `set` function

**Comment by AmaiKinono** [comment]
Sorry I misspelled it. It's `customize-set-variable`. You need to do this:

``` emacs-lisp
(customize-set-variable 'awesome-tab-ace-keys '(?j ?k ?h ?g ?d ?f))
```

And I tried and find that `setq` before requiring does not work, but `general-setq` works. So you can choose one of the latter 2 ways.

**Comment by jiahut** [comment]
`customize-set-variable` works

good job @AmaiKinono  thinks.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-tab/commit/017f21b861e0b25e8a9462fe73b226d992780c98 

Thanks for report.

**Comment by AmaiKinono** [comment]
@manateelazycat I don't think put `h` and `g` in the default value is a good idea. I use a laptop all the time so maybe I don't have a concept of how many tags can a normal screen have. But even it's needed to deal with that many tabs, add `l` and `s` is better than `h` and `g`. Since with ace sequences like `jh` or `fg`, you have to use single finger twice, but with `l` and `s`, you never need to move your hand.

**Comment by manateelazycat** [comment]
可以改成 l 或者 s, 我不想默认 ace-jump 就报错，你提交一个新的 PR 来改进这个问题吧。
