### ISSUE TITLE
Feature request: make tab links work in dumb terminals

### ISSUE THREAD

**Issue by paxperscientiam** [manateelazycat/awesome-tab#55]
Hello, awesome-tab is ... awesome. Works great in cocoa build of emacs and it's helpful in dumb terminals too. One seeming deficit is that clicking tabs in dumb terminal does not cause awesome-tab to switch to the associated buffer.

It seems that this should be possible as given that, for example, the built-in emacs documentation has internal links that lead to different buffers.

Thank you.

**Comment by manateelazycat** [comment]
Thank you very much for your feedback.

I don't need terminal, so this issue will not be resolved in a short time, I expect Emacs hackers use terminals to help fix this problem.

**Comment by paxperscientiam** [comment]
All the same, thanks for sharing.

**Comment by AmaiKinono** [comment]
Just a suggestion, how about using the keyboard? We have `awesome-tab-ace-jump` that's more convenient then the mouse.
