### ISSUE TITLE
face are not persistent

### ISSUE THREAD

**Issue by adouzzy** [manateelazycat/awesome-tab#57]
`The` custom-face works but restore to default after I switch buffer.
Please see examples below.
```

(use-package awesome-tab
  ;;https://github.com/manateelazycat/awesome-tab
  :load-path "~/.emacs.d/opt/awesome-tab/"
  :custom-face
  (awesome-tab-selected ((t (:background "#4a4c4d" :foreground "#e1d5bd" :height 80))))
  (awesome-tab-unselected ((t (:background "#333637" :foreground "#9c9179" :height 60))))

)

```

**Comment by manateelazycat** [comment]
because awesome-tab color chang with current theme，you cannot customize it

**Comment by adouzzy** [comment]
Actually, my intention is to set awesome-tab-face-height.
This face got reset to default after I switch tab.
`
(use-package awesome-tab
  ;;https://github.com/manateelazycat/awesome-tab
  :load-path "~/.emacs.d/opt/awesome-tab/"
  :custom-face
  (awesome-tab-face-height 80)
`

**Comment by maronin** [comment]
comment out the lines around 770 in awesome-tab.el, where the face height is being set.
