### ISSUE TITLE
[Feature Request] : Edition without mousewheel dependency for Termux(android)

### ISSUE THREAD

**Issue by ibnishak** [manateelazycat/awesome-tab#6]
First of all, great work. I have been using it on my Emacs for some time now. 

In Android, Emacs is compiled without mwheel.el, which is fair. Please release an edition without the mouse-wheel dependencies.

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/awesome-tab/commit/f2244194b6f729b26701e65ce24376299bf10a3c
