### ISSUE TITLE
`ivy-switch-buffer-at-current-group`  function

### ISSUE THREAD

**Issue by jiahut** [manateelazycat/awesome-tab#62]
After a little, I always have many tabs in a group, I usually use `ivy-switch-buffer` to switch them, but most of the times I just switch in the current group, and I can switch group with `awesome-tab-counsel-switch-group`

Can provide some helper function like `ivy-switch-buffer-at-current-group` which had been filtered with the current group already.

**Comment by manateelazycat** [comment]
You can implement this function reference function awesome-tab-kill-all-buffers-in-current-group

**Comment by jiahut** [comment]
implement this function, but it running very slowly

```
(defun awesome-tab-switch-tab-with-current-group ()
   "Switch tab with current awesome-group"
  (interactive)
  (setq current-group-name (cdr (awesome-tab-selected-tab (awesome-tab-current-tabset t))))
  (ivy-read "tabs: "
            (mapcar #'buffer-name  (remove-if-not (lambda (buffer) (with-current-buffer buffer
                                                                 (string-equal current-group-name (cdr (awesome-tab-selected-tab (awesome-tab-current-tabset t)))))) (buffer-list)))
            :action '(1 ;; index (1 based) of the default action
                      ("s" (lambda (x)
                             (switch-to-buffer x)) "switch"))))

```
