### ISSUE TITLE
TABs not showing despite I see place reserved for them

### ISSUE THREAD

**Issue by artemkovalyov** [manateelazycat/awesome-tab#65]
After pulling the latest version of awesome-tab they stopped working for me. I can see place for tabs reserved and my key-bindings still work, but tabs itself are invisible. I changed nothing in my configs and tested it on 2 laptops. One was a fresh install with my configs, another where I used and older version that worked. When I fetched it broke there as well.
```
(use-package awesome-tab
  :load-path
  (lambda () (concat user-emacs-directory "user-packages/awesome-tab/"))
  :init
  (require 'awesome-tab)
  :bind
  ("M-s-l" . awesome-tab-forward)
  ("M-s-j" . awesome-tab-backward)
  :config
  (setq awesome-tab-style "bar")
  (awesome-tab-mode t))
```

**Comment by manateelazycat** [comment]
Did you install all-the-icons ?

**Comment by artemkovalyov** [comment]
I haven't seen they are a dependency from the doc. I'll try it out. I like the tabs clean and simple, so I didn't bother with icons at all.

**Comment by manateelazycat** [comment]
Can you revert this patch https://github.com/manateelazycat/awesome-tab/commit/47f2f5e530354064c1cf9df0270bcf4f33c09bb1 and try again?

I guess this patch cause your problem, thanks for feedback!

**Comment by manateelazycat** [comment]
I believe newest version has fix your problem.
