### ISSUE TITLE
Mouse Click on tab not working

### ISSUE THREAD

**Issue by dc-rose** [manateelazycat/awesome-tab#66]
Hi,
All seems to be working fine except that when I click on the tab I get the following error
Wrong type argument: window-live-p, nil
if I click on the small area just below the text (still on the tab....just) then it works fine but if I click anywhere else then I get the error and the tab doesn't change to another buffer. I am using windows 10 and emacs 26.3. I have all-the-icons.el along with the fonts which have been installed I also have memoize.el as this also seemed to be a requirement.
init.el is as below and no errors on startup

(require 'awesome-tab)
(require 'all-the-icons)
(setq inhibit-compacting-font-caches t)
(awesome-tab-mode t)

Any help appreciated thanks

**Comment by manateelazycat** [comment]
M-x toggle-debug-on-error
Then paste content of BackTrace buffer.

Thanks for feedback.

**Comment by dc-rose** [comment]
As requested:
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  select-window(nil)
  (lambda (event) (interactive "e") (select-window (window-at (cadr (mouse-position)) (cddr (mouse-position)) (car (mouse-position)))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs))))((mouse-1 (#<window 3 on *scratch*> header-line (75 . 10) 785825468 (#("  *Messages*  " 0 1 (face awesome-tab-unselected display (image :type xpm :data "/* XPM */ static char * wave_right[] = { \"11 22 3 1\", \"0 c None\", \"1 c #ffffffffffff\", \"2 c None\",\"11111111112\",\"11111111100\",\"11111111000\",\"11111112000\",\"11111110000\",\"11111120000\",\"11111100000\",\"11111100000\",\"11111200000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11112000000\",\"11110000000\",\"11110000000\",\"11120000000\",\"11100000000\",\"11200000000\",\"20000000000\",};" :scale 1 :ascent center :face nil) local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand) 1 2 (face (:inherit (:family "FontAwesome" :height 1.08) :background "#e6e6e6") font-lock-face (:family "FontAwesome" :height 1.08) display (raise -0.12) rear-nonsticky t local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand) 2 14 (face awesome-tab-unselected local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand) 14 15 (face awesome-tab-unselected display (image :type xpm :data "/* XPM */ static char * wave_left[] = { \"11 22 3 1\", \"0 c None\", \"1 c #ffffffffffff\", \"2 c None\",\"21111111111\",\"00111111111\",\"00011111111\",\"00021111111\",\"00001111111\",\"00002111111\",\"00000111111\",\"00000111111\",\"00000211111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000021111\",\"00000001111\",\"00000001111\",\"00000002111\",\"00000000111\",\"00000000211\",\"00000000002\",};" :scale 1 :ascent center :face nil) local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand)) . 7) nil (7 . -1) nil (2 . 10) (10 . 20))))
  funcall-interactively((lambda (event) (interactive "e") (select-window (window-at (cadr (mouse-position)) (cddr (mouse-position)) (car (mouse-position)))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))) (mouse-1 (#<window 3 on *scratch*> header-line (75 . 10) 785825468 (#("  *Messages*  " 0 1 (face awesome-tab-unselected display (image :type xpm :data "/* XPM */ static char * wave_right[] = { \"11 22 3 1\", \"0 c None\", \"1 c #ffffffffffff\", \"2 c None\",\"11111111112\",\"11111111100\",\"11111111000\",\"11111112000\",\"11111110000\",\"11111120000\",\"11111100000\",\"11111100000\",\"11111200000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11111000000\",\"11112000000\",\"11110000000\",\"11110000000\",\"11120000000\",\"11100000000\",\"11200000000\",\"20000000000\",};" :scale 1 :ascent center :face nil) local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand) 1 2 (face (:inherit (:family "FontAwesome" :height 1.08) :background "#e6e6e6") font-lock-face (:family "FontAwesome" :height 1.08) display (raise -0.12) rear-nonsticky t local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand) 2 14 (face awesome-tab-unselected local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand) 14 15 (face awesome-tab-unselected display (image :type xpm :data "/* XPM */ static char * wave_left[] = { \"11 22 3 1\", \"0 c None\", \"1 c #ffffffffffff\", \"2 c None\",\"21111111111\",\"00111111111\",\"00011111111\",\"00021111111\",\"00001111111\",\"00002111111\",\"00000111111\",\"00000111111\",\"00000211111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000011111\",\"00000021111\",\"00000001111\",\"00000001111\",\"00000002111\",\"00000000111\",\"00000000211\",\"00000000002\",};" :scale 1 :ascent center :face nil) local-map (keymap (header-line keymap (mouse-1 lambda (event) (interactive "e") (select-window (window-at (cadr ...) (cddr ...) (car ...))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))) pointer hand)) . 7) nil (7 . -1) nil (2 . 10) (10 . 20))))
  call-interactively((lambda (event) (interactive "e") (select-window (window-at (cadr (mouse-position)) (cddr (mouse-position)) (car (mouse-position)))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))) nil nil)
  command-execute((lambda (event) (interactive "e") (select-window (window-at (cadr (mouse-position)) (cddr (mouse-position)) (car (mouse-position)))) (awesome-tab-buffer-select-tab (quote (#<buffer *Messages*> . Emacs)))))
