### ISSUE TITLE
Use something other than font-lock-doc/comment-face for the foreground color?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tab#77]
Some themes have really dimmed/weird color for docstrings/comments, like:

![image](https://user-images.githubusercontent.com/28714352/77249145-08f05700-6c7a-11ea-82f0-15044db23243.png)
(doom-one-light)

![image](https://user-images.githubusercontent.com/28714352/77249185-4c4ac580-6c7a-11ea-81d4-bbb24c9f1dfd.png)
(doom-solarized-light)

With these themes the tabs aren't easy to read. Can we do this in the original way, where the colors are calculated based on the `default` face?

**Comment by manateelazycat** [comment]
原来那种方式，标题栏太鲜艳太丑了。

可以把 blend 的值暴露出来，如果不不明显，可以降低 blend 的值就好了。

**Comment by manateelazycat** [comment]
awesome-tab-dark-unselected-blend 和 awesome-tab-light-unselected-blend 这两个值越低，分界越明显。

**Comment by AmaiKinono** [comment]
我指的不是背景色而是前景色

**Comment by manateelazycat** [comment]
> 我指的不是背景色而是前景色

主题这个不好说，因为每个主题的用色方法都不一样，可以把前景色暴露成选项，不喜欢可以自己定制。
