### ISSUE TITLE
Feature Request: Hide Tabbar for autocompletions

### ISSUE THREAD

**Issue by Volker-Weissmann** [manateelazycat/awesome-tab#82]
If you have awesome-tab installed, hit M-x, type something and hit tab, you get an auto completion list that looks something like this:
![image](https://user-images.githubusercontent.com/39418860/79979644-1f204b80-84a2-11ea-8478-c3697f59db35.png)

I think that the the lower tabbar should be hidden.

**Comment by manateelazycat** [comment]
Please read https://github.com/manateelazycat/awesome-tab#hiderules
