### ISSUE TITLE
i set  awesome-tab-style is slant,but tab style no change

### ISSUE THREAD

**Issue by zcjava** [manateelazycat/awesome-tab#87]
in spacemacs,i set  awesome-tab-style is slant , but tab style no change.
config:

(require 'awesome-tab)
(awesome-tab-mode t)
(setq awesome-tab-style "slant")

**Comment by manateelazycat** [comment]
that's old version feature, current version no tab style any more

**Comment by zcjava** [comment]
so  tab donnot change?

**Comment by manateelazycat** [comment]
Yes, current version have one style, is default style.
