### ISSUE TITLE
awesome-tab does not work wiht Emacs Ipython Notebook

### ISSUE THREAD

**Issue by Volker-Weissmann** [manateelazycat/awesome-tab#88]
How to reproduce:
Install awesome-tab and  [EIN]( https://github.com/millejoh/emacs-ipython-notebook)
Open a new notebook and your scrren should look something like:
![image](https://user-images.githubusercontent.com/39418860/82256572-e10a3080-9956-11ea-9397-17b158e9cb04.png)
If you run M-x awesome-tab-forward it looks something like:
![image](https://user-images.githubusercontent.com/39418860/82256820-4cec9900-9957-11ea-8b2c-d4c1f2242ad8.png)
Which is how it should look like.
If you run M-x awesome-tab-forward a second time it looks something like:
![image](https://user-images.githubusercontent.com/39418860/82256927-74436600-9957-11ea-8314-811d18756c9f.png)
Which is suboptimal (because there is no longer a tabbar displayed), but still ok. But if you run M-x awesome-tab-forward a third time, it won't switch to the next tab.

**Comment by manateelazycat** [comment]
It's not bug of awesome-tab.

If some buffer not display tab anymore, maybe buffer name match "hide rule" that define in function ```awesome-tab-hide-tab```

You can customize ```awesome-tab-hide-tab``` like I doc in README for you need.

**Comment by Volker-Weissmann** [comment]
Shouldn't M-x awesome-tab-forward still switch to the next tab?

**Comment by manateelazycat** [comment]
> Shouldn't M-x awesome-tab-forward still switch to the next tab?

Switch always work, looks README about hide rule.

**Comment by Volker-Weissmann** [comment]
Ok, thank you.
