### ISSUE TITLE
awesome-tab不生效

### ISSUE THREAD

**Issue by zcjava** [manateelazycat/awesome-tab#89]
更新了最新的版本，不知道为啥只有在你在group rule里面定义的org mode 、dir mode 、magic mode才能识别和使用awesome-tab.其他的模式和文件下都没办法识别(tab栏上面没有任何文件名字显示的) 。
我特意重新安装了。也没发解决这个问题】

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/82857105-96824880-9f42-11ea-8bda-dde623d6d728.png)

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/82857135-a8fc8200-9f42-11ea-8fc0-7fea1b677033.png)

**Comment by zcjava** [comment]
第一个图是python文件，没法识别，awesome-tab 没有任何显示。我已经设置了awesome tab mode.还是无效， 第二张图是他可以识别message org等

**Comment by manateelazycat** [comment]
emacs -Q 排除试一下
