### ISSUE TITLE
How about publishing to Melpa?

### ISSUE THREAD

**Issue by 3tty0n** [manateelazycat/awesome-tab#92]
Do authors/contributors have a plan to publish this package to melpa?

**Comment by manateelazycat** [comment]
No I don't like MELPA, thanks

**Comment by phipsgabler** [comment]
Just saving this for future readers: I use `quelpa`'s `use-package` integration to streamline installation of non-Melpa packages like this one:

```
(use-package awesome-tab
  :quelpa (awesome-tab :fetcher github :repo "manateelazycat/awesome-tab")
  ...)
```
